# Generated by Django 4.2.7 on 2026-09-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_reduce_free_trial_to_ten_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='plan_type',
            field=models.CharField(choices=[('FREE', 'Free Trial (10 days)'), ('MONTHLY', 'Monthly – GH₵ 200/month'), ('YEARLY', 'Yearly – GH₵ 2,200/year (2 months free)')], default='MONTHLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('FREE', 'Free Trial (10 days)'), ('MONTHLY', 'Monthly – GH₵ 200/month'), ('YEARLY', 'Yearly – GH₵ 2,200/year (2 months free)')], default='FREE', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('FREE', 'Free Trial (10 days)'), ('MONTHLY', 'Monthly – GH₵ 200/month'), ('YEARLY', 'Yearly – GH₵ 2,200/year (2 months free)')], default='FREE', max_length=20),
        ),
    ]
