# Generated by ChatGPT on 2026-07-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0002_lessonresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonresource',
            name='class_instance',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='lesson_resources',
                to='schools.class',
            ),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='slot',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='resources',
                to='timetable.lessonslot',
            ),
        ),
    ]
