# Generated by Django 4.2.7 on 2026-09-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_lessonresource_classinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresource',
            name='resource_type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Image'), ('document', 'Document'), ('file', 'File')], default='file', max_length=20),
        ),
    ]
