# Generated by Django 4.2.7 on 2026-07-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_system_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
