# Generated by Django 4.2.7 on 2026-07-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_weeklybill'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='feepayment',
            name='unique_daily_fee_per_student_per_day',
        ),
    ]
