# Generated by Django 4.2.7 on 2026-07-19 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0017_school_student_can_pay_online'),
        ('students', '0010_enhanced_promotion_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartSMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('ATTENDANCE_LOW', 'Attendance Low'), ('EXAM_POOR', 'Exam Poor'), ('FEE_REMINDER', 'Fee Reminder'), ('RISK_ALERT', 'Risk Alert'), ('POSITIVE_FEEDBACK', 'Positive Feedback')], max_length=20)),
                ('message', models.CharField(max_length=160)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_sms_logs', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_sms_logs', to='schools.term')),
            ],
            options={
                'db_table': 'core_smart_sms_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('STUDENT_REPORT', 'Student Report'), ('LESSON_PLAN', 'Lesson Plan'), ('CLASS_INSIGHTS', 'Class Insights')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='schools.class')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_reports', to='schools.term')),
            ],
            options={
                'db_table': 'core_ai_generated_reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('EXCELLING', 'Excelling')], default='LOW', max_length=10)),
                ('attendance_score', models.FloatField(default=100.0)),
                ('academic_score', models.FloatField(default=100.0)),
                ('fee_score', models.FloatField(default=100.0)),
                ('risk_factors', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profiles', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profiles', to='schools.term')),
            ],
            options={
                'db_table': 'core_student_risk_profiles',
                'ordering': ['-calculated_at'],
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('REGULAR_ABSENCE', 'Regular Absence'), ('DECLINING', 'Declining'), ('IMPROVING', 'Improving'), ('CONSISTENT', 'Consistent')], default='CONSISTENT', max_length=20)),
                ('absent_day', models.CharField(blank=True, max_length=10, null=True)),
                ('trend', models.CharField(choices=[('IMPROVING', 'Improving'), ('DECLINING', 'Declining'), ('STABLE', 'Stable')], default='STABLE', max_length=10)),
                ('consecutive_absences', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('alert_needed', models.BooleanField(default=False)),
                ('analysed_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_insights', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_insights', to='schools.term')),
            ],
            options={
                'db_table': 'core_attendance_insights',
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='AcademicTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_trend', models.CharField(choices=[('IMPROVING', 'Improving'), ('DECLINING', 'Declining'), ('STABLE', 'Stable')], default='STABLE', max_length=10)),
                ('percentage_change', models.FloatField(default=0.0)),
                ('best_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('worst_subject', models.CharField(blank=True, max_length=100, null=True)),
                ('subjects_declined', models.JSONField(default=list)),
                ('subjects_improved', models.JSONField(default=list)),
                ('alert_needed', models.BooleanField(default=False)),
                ('alert_reason', models.TextField(blank=True, null=True)),
                ('analysed_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_trends', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_trends', to='schools.term')),
            ],
            options={
                'db_table': 'core_academic_trends',
                'unique_together': {('student', 'term')},
            },
        ),
    ]
